# Generated by Django 3.0.2 on 2020-03-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
