# Generated by Django 3.0.4 on 2020-03-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='description',
            field=models.TextField(),
        ),
    ]
