# Generated by Django 3.0.2 on 2020-03-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_auto_20200310_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopprofile',
            old_name='address',
            new_name='address_line1',
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='address_line2',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='address_line3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='country',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='town_city',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
