# Generated by Django 3.0.4 on 2020-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SHOPKEEPER', 'shopkeeper'), ('DELIVERY_PERSON', 'delivery person'), ('CUSTOMER', 'customer')], default='CUSTOMER', max_length=20, verbose_name='user role'),
        ),
    ]
